version: '3.1'

services:
  app:
    image: 'docker-kislab-app:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - mariadb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/kislab
      SPRING_DATASOURCE_USERNAME: kislab
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "${APP_PORT:-8080}:8080"
    restart: unless-stopped
    networks:
      - default

  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb
    environment:
      MARIADB_USER: kislab
      MARIADB_PASSWORD: 123
      MARIADB_DATABASE: kislab
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge